# services.yaml

parameters:
    directorio_imagenes: '%kernel.project_dir%/public/uploads/productos'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Otros servicios
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
